version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres-olist-database
    
    volumes:
      - .:/olist_dw:rw
    working_dir: /olist_dw
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: olist
    ports:
      - 5434:5432
    restart: always
